### ISSUE TITLE
功能修复

### ISSUE THREAD

**Issue by zjj** [github-amazingboy/AwesomeRA#113]
1. 自主系统接入2页接入ra，查询，审计（接口参见csyapi）http://csyapi.qihoo.net/project/200/interface/api/11497
2. revoke reason 加入sysmeta接口 参见返回 http://csyapi.qihoo.net/project/200/interface/api/13477
3. 已下载证书get添加ca和crl链接  参见csyapi http://csyapi.qihoo.net/project/200/interface/api/11692
4. 吊销增加revoke_reason请求字段 http://csyapi.qihoo.net/project/200/interface/api/11557

**Comment by zjj** [comment]
@holyjunhui

**Comment by holyjunhui** [comment]
fix
