### ISSUE TITLE
字段显示问题合集

### ISSUE THREAD

**Issue by github-amazingboy** [github-amazingboy/AwesomeRA#114]
### 下载页面
![证书下载页面显示](https://user-images.githubusercontent.com/34153374/106841825-ce4eac00-66dd-11eb-880e-cc601f61cdfa.png)

### 证书详情页
![证书详情页](https://user-images.githubusercontent.com/34153374/106842289-b6c3f300-66de-11eb-9162-28635d78505a.png)

### 过期证书查询页

![过期证书查询页](https://user-images.githubusercontent.com/34153374/106843072-25ee1700-66e0-11eb-87e9-d3971d99daeb.png)

**Comment by github-amazingboy** [comment]
### 机构管理
![新增的时候让我填，又不显示我填的](https://user-images.githubusercontent.com/34153374/106849971-9e5bd480-66ee-11eb-95bf-3090a793a261.png)

**Comment by github-amazingboy** [comment]
![图片](https://user-images.githubusercontent.com/34153374/106867342-6f525c80-6708-11eb-9062-f940a2830059.png)

**Comment by github-amazingboy** [comment]
### 全站不要写 无 字
![全站不要写 无 字](https://user-images.githubusercontent.com/34153374/106086423-13626380-615d-11eb-8dea-e37979548088.jpg)

**Comment by github-amazingboy** [comment]
![图片](https://user-images.githubusercontent.com/34153374/106981812-b179ad80-679d-11eb-9007-86a58f7eead5.png)

**Comment by github-amazingboy** [comment]
![用户类型显示](https://user-images.githubusercontent.com/34153374/106097920-19633f00-6173-11eb-9b1b-51424941e7f5.png)

**Comment by github-amazingboy** [comment]
![证书公钥文件](https://user-images.githubusercontent.com/34153374/106105382-e2932600-617e-11eb-870c-c2832da5751f.png)

**Comment by github-amazingboy** [comment]
### 申请查询详情页
![申请查询](https://user-images.githubusercontent.com/34153374/106104241-24bb6800-617d-11eb-9c93-f8ad49ace9b2.png)

**Comment by github-amazingboy** [comment]
![图片](https://user-images.githubusercontent.com/34153374/106987010-8b590b00-67a7-11eb-815f-9ebc41b2b3e7.png)

**Comment by holyjunhui** [comment]
fix

**Comment by holyjunhui** [comment]
机构管理有问题

**Comment by holyjunhui** [comment]
all fix
