### ISSUE TITLE
CA证书RA异常处理流程

### ISSUE THREAD

**Issue by zjj** [github-amazingboy/AwesomeRA#123]
证书同步接口将ca证书状态同步给RA, 暂时有下面异常需考虑

如果ra下载了证书，但是用户下载到ukey的时候失败了，ra这时候提示的是未下载，ca端已经显示了使用中。
ra同步状态就不对了。

**Comment by github-amazingboy** [comment]
如果是用户下载到ukey失败， 这是用户的环境问题导致无法安装证书，解决这个问题是换个环境，或者重新下单。
CA 端签发了，CA上的状态肯定是使用中，这没有问题。
RA 端应该给一个下载异常/或者安装异常的状态，证书的信息也还是按正常情况入库，这是前端ukey环境问题，非CA或RA系统的问题。

总结：
CA上是使用中  RA上是 安装异常 ， 这个两个状态是对应的上。
